package models;

public enum School {
	SCHOOL_OF_GEOLOGY,
	BUSINESS_SCHOOL,
	SCHOOL_OF_IT_AND_ENGINEERING,
	SCHOOL_OF_ENERGY,
	SCHOOL_OF_NATURAL_AND_SOCIAL_SCIENCES, 
	INTERNATION_SCHOOL_OF_ECONOMICS,
	KAZAKHSTAN_MARITIME_ACADEMY,
	SCHOOL_OF_APPLIED_MATHEMATICS,
	SCHOOL_OF_CHEMICAL_ENGINEERING,
	SCHOOL_OF_MATERIALS_SCIENCE,
}
